export const shoe = [
  {
    id: "AIR_MAX_1",
    name: "AIR MAX 1",
    img: "AIRMAX1.png",
    price: 1309,
    quantity: 0,
    added: false,
  },
  {
    id: "AIR_TRAINER_1_SP",
    name: "AIR TRAINER 1 SP",
    img: "AIRTRAINER1SP.png",
    price: 1030,
    quantity: 0,
    added: false,
  },
  {
    id: "AIR_MAX2_CB",
    name: "AIR MAX2 CB",
    img: "AIRMAX2CB.png",
    price: 249,
    quantity: 0,
    added: false,
  },
  {
    id: "DUNK_LOW_RETRO_NN",
    name: "AIR MAX 2017",
    img: "DUNKLOWRETRONN.png",
    price: 185,
    quantity: 0,
    added: false,
  },
  {
    id: "AIR_MAX_95_QS",
    name: "AIR MAX 95 QS ",
    img: "AIRMAX95QS.png",
    price: 130,
    quantity: 0,
    added: false,
  },
  {
    id: "AIR_MAX_97",
    name: "AIR MAX 97",
    img: "AIRMAX97.png",
    price: 235,
    quantity: 0,
    added: false,
  },
  {
    id: "AIR_VAPORMAX_PLUS",
    name: "AIR VAPORMAX PLUS",
    img: "AIRVAPORMAXPLUS.png",
    price: 215,
    quantity: 0,
    added: false,
  },
  {
    id: "TERRA_VISTA",
    name: "TERRA VISTA ",
    img: "TERRAVISTA.png",
    price: 110,
    quantity: 0,
    added: false,
  },
  {
    id: "VAPORWAFFLE",
    name: "VAPORWAFFLE",
    img: "VAPORWAFFLE.png",
    price: 390,
    quantity: 0,
    added: false,
  },
  {
    id: "SB_DUNK_HIGH",
    name: "SB DUNK HIGH",
    img: "SBDUNKHIGH.png",
    price: 250,
    quantity: 0,
    added: false,
  },
  {
    id: "DUNK_HIGH",
    name: "DUNK HIGH",
    img: "DUNKHIGH.png",
    price: 200,
    quantity: 0,
    added: false,
  },
  {
    id: "LEBRON_9",
    name: "LEBRON 9",
    img: "LEBRON9.png",
    price: 239,
    quantity: 0,
    added: false,
  },
];
